# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160618_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filesize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
