# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttoimage',
            name='insecure',
            field=models.TextField(null=True),
        ),
    ]
