# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160605_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecttoimage',
            options={'managed': True},
        ),
    ]
