# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_treasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='ip',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
