# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20160609_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='oid',
            field=models.ForeignKey(db_column='oid', default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Image'),
        ),
    ]
