# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_treasure_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='mail',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='uri',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='ip',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
