# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20160611_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='files',
        ),
    ]
