# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_treasure_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecttoimage',
            options={'managed': True},
        ),
    ]
